name: hurricane
channels:
  - conda-forge
  - defaults
dependencies:
  - xarray
  - netcdf4
  - beautifulsoup4
  - cmocean
  - erddapy
  - python=3.7
  - cartopy
  - matplotlib
  - dask
  - dash
  - pip
  - ipython
  - tqdm
  - oceans
  - motuclient
  - geopandas